jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  disableRememberMe: false
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: true
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: false
  scmCheckoutRetryCount: 0
  slaveAgentPort: 50000
  systemMessage: |+
    Jenkins configured automatically by Jenkins Configuration as Code Plugin
  updateCenter:
    sites:
    - id: "ctech-jenkins-plugins"
      url: "http://jenkins-update-site.jjc-devops.com/artifactory/ctech-jenkins-plugins/update-center/SNAPSHOT/update-center.json"
    - id: "default"
      url: "http://updates.jenkins-ci.org/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
security:
  downloadSettings:
    useBrowser: false
  remotingCLI:
    enabled: false
  sSHD:
    port: -1
unclassified:
  ansiColorBuildWrapper:
    colorMaps:
    - black: "#000000"
      blackB: "#4C4C4C"
      blue: "#1E90FF"
      blueB: "#4682B4"
      cyan: "#00CDCD"
      cyanB: "#00FFFF"
      green: "#00CD00"
      greenB: "#00FF00"
      magenta: "#CD00CD"
      magentaB: "#FF00FF"
      name: "xterm"
      red: "#CD0000"
      redB: "#FF0000"
      white: "#E5E5E5"
      whiteB: "#FFFFFF"
      yellow: "#CDCD00"
      yellowB: "#FFFF00"
    - black: "#000000"
      blackB: "#555555"
      blue: "#0000AA"
      blueB: "#5555FF"
      cyan: "#00AAAA"
      cyanB: "#55FFFF"
      defaultBackground: 0
      defaultForeground: 7
      green: "#00AA00"
      greenB: "#55FF55"
      magenta: "#AA00AA"
      magentaB: "#FF55FF"
      name: "vga"
      red: "#AA0000"
      redB: "#FF5555"
      white: "#AAAAAA"
      whiteB: "#FFFFFF"
      yellow: "#AA5500"
      yellowB: "#FFFF55"
    - black: "black"
      blackB: "black"
      blue: "blue"
      blueB: "blue"
      cyan: "cyan"
      cyanB: "cyan"
      green: "green"
      greenB: "green"
      magenta: "magenta"
      magentaB: "magenta"
      name: "css"
      red: "red"
      redB: "red"
      white: "white"
      whiteB: "white"
      yellow: "yellow"
      yellowB: "yellow"
    - black: "#2E3436"
      blackB: "#2E3436"
      blue: "#3465A4"
      blueB: "#3465A4"
      cyan: "#06989A"
      cyanB: "#06989A"
      defaultBackground: 0
      defaultForeground: 7
      green: "#4E9A06"
      greenB: "#4E9A06"
      magenta: "#75507B"
      magentaB: "#75507B"
      name: "gnome-terminal"
      red: "#CC0000"
      redB: "#CC0000"
      white: "#D3D7CF"
      whiteB: "#D3D7CF"
      yellow: "#C4A000"
      yellowB: "#C4A000"
  artifactoryBuilder:
    useCredentialsPlugin: false
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        manageHooks: false
  casCGlobalConfig:
    configurationPath: "https://raw.githubusercontent.com/ylikhach/jcasc_demo/master/jenkins.yaml?token=AM3FXPVDHBIH3J67CIWSKRS5JPIAO"
  extendedEmailPublisher:
    adminRequiredForTemplateTesting: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: 0
    precedenceBulk: false
    smtpAuthPassword: "****"
    useSsl: false
    watchingEnabled: false
  gitHubPluginConfig:
    hookUrl: "https://dev-ctech-ci.jjc-devops.com/github-webhook/"
  gitSCM:
    createAccountBasedOnEmail: false
  globalSettings:
    failOnCorrupt: false
    noAuthors: false
    quietMode: false
  globalVaultConfiguration:
    configuration:
      vaultCredentialId: "default-global-vault-token"
      vaultUrl: "http://ctech-vault.jjc-devops.com:50000"
  groovy:
    installations:
    - name: "GROOVY2"
      properties:
      - installSource:
          installers:
          - groovyInstaller:
              id: "2.4.7"
  location:
    adminAddress: "jenkins@localhost"
    url: "https://dev-ctech-ci.jjc-devops.com/"
  mailer:
    adminAddress: "jenkins@localhost"
    charset: "UTF-8"
    defaultSuffix: "@its.jnj.com"
    useSsl: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 0
  timestamperConfig:
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  triggeredBuildSelector:
    globalUpstreamFilterStrategy: UseOldest
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  groovyInstallation:
    installations:
    - name: "GROOVY2"
      properties:
      - installSource:
          installers:
          - groovyInstaller:
              id: "2.4.7"
  jdk:
    installations:
    - name: "jdk"
      properties:
      - installSource:
          installers:
          - zip:
              url: "http://jenkins-update-site.jjc-devops.com/artifactory/jdk/jdk-9.0.4_linux-x64_bin.tar.gz"
  maven:
    installations:
    - name: "maven3"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.3.9"
jobs:
  - script: >
      folder('DEV_environment')
  - script: >
      pipelineJob('DEV_environment/CanvasX') {
        pipelineJob('testjobs/default-agent') {
          definition {
            cps {
              script("""\
                pipeline {
                  agent any
                  stages {
                  steps {
                    echo "hello"
                    }
                  }
                }
              }""".stripIndent())
            }
          }
        }