jenkins:
  systemMessage: |+
    Jenkins configured automatically by Jenkins Configuration as Code Plugin
jobs:
  - script: >
      folder('DEV_environment')
  - script: >
      pipelineJob('DEV_environment/CanvasX') {
          definition {
            cps {
              script("""\
                pipeline {
                  agent any
                  stages {
                    stage('Smoke run') {
                      steps {
                        echo "hello"
                      }
                    }
                  }
                }
              """.stripIndent())
            }
          }
        }